### ISSUE TITLE
Invalid attribute apiVersion in build_object_reference()

### ISSUE THREAD

**Issue by olivier-mauras** [zalando-incubator/kopf#166]
## Actual Behavior
``` text
[2019-08-06 05:50:32,627] kopf.objects         [ERROR   ] [xxx-dev/tiller] Handler 'sa_delete' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 387, in _execute
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 478, in _call_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 66, in invoke
    result = await fn(*args, **kwargs)
  File "./ns.py", line 235, in sa_delete
    kopf.info(ns.to_dict(), reason='SA_DELETED', message='Managed service account got deleted')
  File "/usr/local/lib/python3.7/site-packages/kopf/engines/posting.py", line 79, in info
    event(obj, type='Normal', reason=reason, message=message)
  File "/usr/local/lib/python3.7/site-packages/kopf/engines/posting.py", line 72, in event
    ref = hierarchies.build_object_reference(obj)
  File "/usr/local/lib/python3.7/site-packages/kopf/structs/hierarchies.py", line 12, in build_object_reference
    apiVersion=body['apiVersion'],
KeyError: 'apiVersion'
``` 

## Steps to Reproduce the Problem
``` python
@kopf.on.delete('', 'v1', 'serviceaccounts', annotations={'custom/created_by': 'namespace-manager'})
async def sa_delete(body, namespace,  **kwargs):
  try:
    api = kubernetes.client.CoreV1Api()
    ns = api.read_namespace(name=namespace)
  except ApiException as err:
    sprint('ERROR', 'Exception when calling CoreV1Api->read_namespace: {}'.format(err))

  kopf.info(ns.to_dict(), reason='SA_DELETED', message='Managed service account got deleted')
  return
```
#######
Culprit lies here in `hierarchies.py`
``` python
def build_object_reference(body):
    """
    Construct an object reference for the events.
    """
    return dict(
        apiVersion=body['apiVersion'],
        kind=body['kind'],
        name=body['metadata']['name'],
        uid=body['metadata']['uid'],
        namespace=body['metadata']['namespace'],
    )
```
As described in https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Namespace.md `apiVersion` attribute should be `api_version`.  
Replacing line 12 with `api_version` makes indeed the above code work but I'm not sure there's other implication before sending you a PR

**Comment by olivier-mauras** [comment]
#168

**Comment by olivier-mauras** [comment]
Oh apparently it's not the API that is inconsistent, but the body returned by on.xxx() handlers of kopf.

Here's an example:
body returned by on.resume/create
``` text
{'apiVersion': 'v1',
 'kind': 'Namespace',
 'metadata': {'annotations': {'cattle.io/status': '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2019-04-29T08:26:31Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2019-04-29T08:26:32Z"}]}',
                              'kopf.zalando.org/last-handled-configuration': '{"spec": '
                                                                             '{"finalizers": '
                                                                             '["kubernetes"]}, '
                                                                             '"annotations": '
                                                                             '{"cattle.io/status": '
                                                                             '"{\\"Conditions\\":[{\\"Type\\":\\"ResourceQuotaInit\\",\\"Status\\":\\"True\\",\\"Message\\":\\"\\",\\"LastUpdateTime\\":\\"2019-04-29T08:26:31Z\\"},{\\"Type\\":\\"InitialRolesPopulated\\",\\"Status\\":\\"True\\",\\"Message\\":\\"\\",\\"LastUpdateTime\\":\\"2019-04-29T08:26:32Z\\"}]}", '
                                                                             '"lifecycle.cattle.io/create.namespace-auth": '
                                                                             '"true"}}}',
                              'lifecycle.cattle.io/create.namespace-auth': 'true''},
              'creationTimestamp': '2019-02-04T12:18:54Z',
              'finalizers': ['controller.cattle.io/namespace-auth'],
              'name': 'trident',
              'resourceVersion': '27520896',
              'selfLink': '/api/v1/namespaces/trident',
              'uid': '0a305ee9-2877-11e9-a525-005056abd413'},
 'spec': {'finalizers': ['kubernetes']},
 'status': {'phase': 'Active'}}
```
body returned directly by the API with a read_namespace call:
``` text
{'api_version': 'v1',
 'kind': 'Namespace',
 'metadata': {'annotations': {'cattle.io/status': '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2019-04-29T08:26:31Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2019-04-29T08:26:32Z"}]}',
                              'kopf.zalando.org/last-handled-configuration': '{"spec": '
                                                                             '{"finalizers": '
                                                                             '["kubernetes"]}, '
                                                                             '"annotations": '
                                                                             '{"cattle.io/status": '
                                                                             '"{\\"Conditions\\":[{\\"Type\\":\\"ResourceQuotaInit\\",\\"Status\\":\\"True\\",\\"Message\\":\\"\\",\\"LastUpdateTime\\":\\"2019-04-29T08:26:31Z\\"},{\\"Type\\":\\"InitialRolesPopulated\\",\\"Status\\":\\"True\\",\\"Message\\":\\"\\",\\"LastUpdateTime\\":\\"2019-04-29T08:26:32Z\\"}]}", '
                                                                             '"lifecycle.cattle.io/create.namespace-auth": '
                                                                             '"true"}}}',
                              'lifecycle.cattle.io/create.namespace-auth': 'true'},
              'cluster_name': None,
              'creation_timestamp': datetime.datetime(2019, 2, 4, 12, 18, 54, tzinfo=tzlocal()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': ['controller.cattle.io/namespace-auth'],
              'generate_name': None,
              'generation': None,
              'initializers': None,
              'name': 'trident',
              'namespace': None,
              'owner_references': None,
              'resource_version': '27520896',
              'self_link': '/api/v1/namespaces/trident',
              'uid': '0a305ee9-2877-11e9-a525-005056abd413'},
 'spec': {'finalizers': ['kubernetes']},
 'status': {'phase': 'Active'}}
```

**Comment by psycho-ir** [comment]
I think that's because of the difference naming in `pykube`(camelCase) has from `kubernetes-client`(snake_case).

so probably if you use the `pykube-ng` instead of `kubernetes-client` this issue should be gone, just as an interim solution.

we need to find a proper way probably to handle these naming mismatches @nolar.

**Comment by nolar** [comment]
Kopf is agnostic of the clients used by the developers (kind of). The only "canonical" reference is the Kubernetes API. The API docs [says the field name is `apiVersion`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#objectreference-v1-core).

This is how Kopf gets it from the API, and passes it to the handlers. And this is how Kopf expects it from the handlers to be passed to the API.

In the base case, there are no Kubernetes clients at all, just the raw dicts, the json parser-serializer, and an HTTP library.

`api_version` is a naming conventions used in the Python Kubernetes client only (in an attempt to follow Python's snake_case convention). I.e., it is a client's issue that it produces and consumes such strange non-API-compatible dicts.

---

Kopf also tries to be friendly to all clients — but to an extent. I'm not sure if bringing the workarounds for literally _all_ clients with their nuances would be a good idea. 

Even for the official client alone (just for the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)), it would mean one of the following:

* Adding the duplicating dict keys (both `apiVersion` & `api_version`), and filtering out the non-canonical forms on the internal use, the canonical forms on the external use — thus increasing the complexity.
* Making special classes for all these structs, with properties as aliases. And so we turn Kopf into a client library with its own K8s object-manipulation DSL — which goes against some principles of API-client neutrality. (Now it runs on plain dicts.)
* Allowing the design and conventions of the official client (sometimes questionable) to dictate the design and conventions of Kopf, making Kopf incompatible with other clients that _do_ follow the canonical API naming.

Neither of this I consider a good solution to the problem.

At the moment, and in my opinion, the best solution is to do nothing, and to let this issue exist (to be solved by the operator developers on the app-level).

**Comment by olivier-mauras** [comment]
@nolar Thanks for the reply.
I'm actually super fine to fix that in my code directly. I guess we can close the PR
