### ISSUE TITLE
Kopf crashes with `concurrent.futures._base.TimeoutError`

### ISSUE THREAD

**Issue by smileisak** [zalando-incubator/kopf#178]
## Expected Behavior

No craches related to the kopf framework.

## Actual Behavior

When developping the kopf based operator in my local machine i'm using personal kubeconfig to authenticate againt Kubernetes API. It works fine no problem.

But when deploying the operator in a GKE cluster, it craches after generating events (create or delete) in my CRD.

## Specifications

  - Platform: GKE
  - Kubernetes version: `v1.12.7-gke.25`
  - Python version:  `3.7.4`
  - Python packages installed: *(use `pip freeze --all`)*

```
adal==1.2.1
aiofiles==0.4.0
aiohttp==3.5.4
aiojobs==0.2.2
asn1crypto==0.24.0
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.1.0
cachetools==3.1.0
certifi==2018.11.29
cffi==1.12.2
chardet==3.0.4
Click==7.0
coloredlogs==10.0
cryptography==2.6.1
decorator==4.4.0
fut==0.4.2
google-api-python-client==1.7.8
google-auth==1.6.3
google-auth-httplib2==0.0.3
httplib2==0.12.1
humanfriendly==4.18
idna==2.8
iso8601==0.1.12
isort==4.3.17
jsonpath-ng==1.4.3
kopf==0.20
kubernetes==8.0.1
more-itertools==6.0.0
multidict==4.5.2
oauth2client==4.1.3
oauthlib==3.0.1
pip==19.1.1
pluggy==0.9.0
ply==3.11
protobuf==3.6.1
py==1.8.0
pyasn1==0.4.5
pyasn1-modules==0.2.4
pycparser==2.19
PyJWT==1.7.1
pykube-ng==0.28
pyotp==2.2.7
pytest==4.3.0
python-anticaptcha==0.3.1
python-dateutil==2.8.0
pytz==2019.1
PyYAML==3.13
requests==2.21.0
requests-oauthlib==1.2.0
rsa==4.0
setuptools==40.6.3
six==1.12.0
tzlocal==2.0.0
uritemplate==3.0.0
urllib3==1.24.1
urllib3-mock==0.3.3
websocket-client==0.55.0
wheel==0.32.3
yarl==1.3.0

```
## Related source code:

kopf/reactor/handling.py

```python
# Sleep strictly after patching, never before -- to keep the status proper.
if delay:
    logger.debug(f"Sleeping for {delay} seconds for the delayed handlers.")
    await asyncio.sleep(delay)
```

```
🦋 ➸  k logs -f -n j2c-operator mast-j2c-operator-5c7955cddd-77dcs
[2019-08-08 16:28:35,257] kopf.clients.auth    [DEBUG   ] Pykube is configured in cluster with service account.
[2019-08-08 16:28:35,290] kopf.clients.auth    [DEBUG   ] Client is configured in cluster with service account.
2019-08-08 16:28:35 mast-j2c-operator-5c7955cddd-77dcs kopf.engines.peering[1] WARNING Default peering object not found, falling back to the standalone mode.
2019-08-08 16:28:53 mast-j2c-operator-5c7955cddd-77dcs kopf.reactor.queueing[1] ERROR functools.partial(<function custom_object_handler at 0x7f46fb0284d0>, lifecycle=<function asap at 0x7f46f8ae2320>, registry=<kopf.reactor.registries.GlobalRegistry object at 0x7f46fb008f90>, resource=Resource(group='renault.org', version='v1', plural='applications'), event_queue=<Queue at 0x7f46f3fff610 maxsize=0>, freeze=<asyncio.locks.Event object at 0x7f46f3ca9e50 [unset]>) failed with an exception. Ignoring the event.
Traceback (most recent call last):
  File "/app/env/lib/python3.7/site-packages/kopf/reactor/queueing.py", line 148, in worker
    await handler(event=event)
  File "/app/env/lib/python3.7/site-packages/kopf/reactor/handling.py", line 136, in custom_object_handler
    await asyncio.sleep(delay)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 595, in sleep
    return await future
concurrent.futures._base.CancelledError
Job closing timed out
job: <Job closed coro=<<coroutine object worker at 0x7f46f04d3710>>>
Traceback (most recent call last):
  File "/app/env/lib/python3.7/site-packages/aiojobs/_job.py", line 89, in _close
    await self._task
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/env/lib/python3.7/site-packages/aiojobs/_job.py", line 89, in _close
    await self._task
  File "/app/env/lib/python3.7/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/app/env/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

```

**Comment by nolar** [comment]
The error in the stack trace happens because the coroutine (`asyncio.sleep()`) is being cancelled. The question is why is it being cancelled at all, and by whom. However, there is nothing in the logs about that.

@smileisak  Can you please try running with `kopf==0.21rc3` (or `0.21rc2`, `0.21rc1` — pre-releases) and with `--verbose` CLI option? These versions include better termination routines with more detailed logging (#156), so we can get some hints on why it is exiting.

**Comment by nolar** [comment]
@smileisak And a couple of other assumptions:

What is the approximate amount of objects/events happening at a time? 10s? 100s? 1000s?

Are there any blocking or synchronous handlers executing longer than 5s? Does playing with `kopf.config.WorkersConfig.worker_idle_timeout` (setting it to 1 or 10 or 60 (default is 5)) affect the stability? You can set it immediately after `import kopf`, on the module level.

**Comment by smileisak** [comment]
@nolar i have the same output using the `kopf==0.21rc3` and `kopf.config.WorkersConfig.worker_idle_timeout = 60`.

```bash
2019-08-08 17:11:44 mast-j2c-operator-797c687dff-vrdwm kopf.objects[1] ERROR Handler 'delete_fn' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/app/env/lib/python3.7/site-packages/kopf/reactor/handling.py", line 400, in _execute
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/app/env/lib/python3.7/site-packages/kopf/reactor/handling.py", line 504, in _call_handler
    **kwargs,
  File "/app/env/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 79, in invoke
    result = await loop.run_in_executor(config.WorkersConfig.get_syn_executor(), real_fn)
concurrent.futures._base.CancelledError
Job closing timed out
job: <Job closed coro=<<coroutine object worker at 0x7ff9ad5be3b0>>>
Traceback (most recent call last):
  File "/app/env/lib/python3.7/site-packages/aiojobs/_job.py", line 89, in _close
    await self._task
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/env/lib/python3.7/site-packages/aiojobs/_job.py", line 89, in _close
    await self._task
  File "/app/env/lib/python3.7/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/app/env/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
```

The operator aims to provision a namespaced multi-tenant environments inside 2 clusters:

1. dev cluster
1. prod cluster

and it communicate with google api to create service accounts, roles and iam bindings

i'm using `subprocess.call` to run helm commands.

Maybe a schema is better to understand the usecase
![j2c-operator](https://user-images.githubusercontent.com/3457118/62727182-2b9a6c00-ba19-11e9-9f40-1bdf5b62098b.png)

So in some cases when creating a new `Application` it will run multiple k8s and gcp api calls and run also some `subprocess.call` for helm commands.

**Comment by nolar** [comment]
@smileisak What I see from these logs, is that it is not about sleeping. The cancellation happens at any random places, i.e. when the task is cancelled from outside.

The task is cancelled in these cases only: Any single one of the "core" tasks (peering, k8s-event posting, "should_stop" waiter, and watching for every resource kind) exits normally or by an exception.

The "should_stop" waiter exits only on SIGINT/SIGTERM, and it would print a log line "Stop-flag is raised. Operator is stopping."

With 0.21rc3, the output is usually like this on any reason of exiting:

```
[2019-08-09 10:40:48,597] kopf.reactor.running [DEBUG   ] Stop-flag is raised. Operator is stopping.
[2019-08-09 10:40:48,598] kopf.reactor.running [DEBUG   ] Root tasks are stopped: finished normally; tasks left: set()
[2019-08-09 10:40:48,598] kopf.reactor.running [DEBUG   ] Hung tasks stopping is skipped: no tasks given.
```

That is strange that you have nothing of that.

---

Another hint is the `TimeoutError` on the "job closing". The "jobs" are used for per-object handlers. The handling in that case is sequential. In this case, it means that it has stuck.

Among all things that stuck, I would first assume that one of the sync-handlers has stuck. And would put the log/print statements into them to see which one is not printing its "returning" message.

---

Which, by the way, happened with `subprocess.call()` for me — unrelated to Kopf. Sometimes, the subprocess exits, but Python does not notice that. It is common for the cases when the subprocesses have some daemon threads/children, so they keep its stdin/stdout/stderr not released, and so Python thinks something is still alive there.

Can you also try replacing all subprocesses' commands to `echo` (i.e. a plain and reliable tool). Does the problem persist?

---

Those are just hypothesis and guesses. It is difficult to say something specific without the exact codebase. Is this j2c-provision-operator open-sourced or closed-source?

**Comment by smileisak** [comment]
@nolar i figured out why this sucks. Since i'm deploying the operator with helm, when i created the helm chart using `helm create <chart-name>`, it adds default `livenessProbe` and `readinessProbe` so kubernetes will kill the pod when readinessProbe is not satisfied.

```bash
message: Back-off 1m20s restarting failed container=j2c-operator pod=mast-j2c-operator-67b699b7cc-lwz5g_j2c-operator(4f131c13-ba89-11e9-9fdc-4201ac10000a)
```

Now after deleting this probes everything works fine ! 
```yaml
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
```

So the bug is not related to `kopf`. Anyway, thank you again for your support. I'd like to have a success story for this project.

About your question `j2c-provision-operator ` is closed-source right now. Maybe in the futre will be opensourced.

**Comment by nolar** [comment]
@smileisak I see. Thanks for clarifying. I will add extra log messages on the reasons of exiting (INFO or WARN level). Specifically, it should be clearly visible that it exits on the SIGTERM signal.
