### ISSUE TITLE
Odd RBAC issues

### ISSUE THREAD

**Issue by sepulworld** [zalando-incubator/kopf#206]
## Expected Behavior

I have been developing a new operator on k8s 1.15.4 (server) I don't seem to have issues (testing from local Docker for Mac).

```
[2019-10-19 06:07:20,004] kopf.clients.auth    [DEBUG   ] Pykube is configured in cluster with service account.
[2019-10-19 06:07:20,013] kopf.clients.auth    [DEBUG   ] Client is configured in cluster with service account.
```

## Actual Behavior

However, deploying same yaml to our dev cluster running v1.14.6 I run into the following error which appears to be RBAC related.
```
[2019-10-19 06:17:16,557] kopf.clients.auth    [DEBUG   ] Pykube is configured in cluster with service account.
[2019-10-19 06:17:16,564] kopf.clients.auth    [DEBUG   ] Client is configured in cluster with service account.
[2019-10-19 06:17:16,635] kopf.reactor.running [ERROR   ] Root task 'watcher of vpcendpoints.trulia.com' is failed: HTTPError('403 Client Error: Forbidden for url: https://10.255.0.1:443/apis/trulia.com/v1/vpcendpoints')
[2019-10-19 06:17:16,635] kopf.reactor.running [DEBUG   ] Root task 'poster of events' is cancelled.
[2019-10-19 06:17:16,635] kopf.reactor.running [DEBUG   ] Root tasks are stopped: finished normally; tasks left: set()
[2019-10-19 06:17:16,635] kopf.reactor.running [DEBUG   ] Hung tasks stopping is skipped: no tasks given.
Traceback (most recent call last):
  File "/usr/local/bin/kopf", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 63, in run
    peering_name=peering_name,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/running.py", line 44, in run
    peering_name=peering_name,
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/running.py", line 79, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/running.py", line 215, in run_tasks
    await _reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/running.py", line 263, in _reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/running.py", line 270, in _root_task_checker
    await coro
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/queueing.py", line 80, in watcher
    async for event in watching.infinite_watch(resource=resource, namespace=namespace):
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/watching.py", line 86, in infinite_watch
    async for event in streaming_watch(resource=resource, namespace=namespace):
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/watching.py", line 101, in streaming_watch
    rsp = fetching.list_objs(resource=resource, namespace=namespace)
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/fetching.py", line 61, in list_objs
    return lst.response
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 186, in response
    return self.query_cache["response"]
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 172, in query_cache
    cache["response"] = self.execute().json()
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 149, in execute
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.255.0.1:443/apis/trulia.com/v1/vpcendpoints
```

## Steps to Reproduce the Problem

Apply on Docker for Mac (k8s 1.15.4 and it works)
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vpcendpoints.trulia.com
spec:
  scope: Namespaced
  group: trulia.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: VPCEndpoint
    plural: vpcendpoints
    singular: vpcendpoint
    shortNames:
      - vpces
      - vpce
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpce-operator-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: vpce-operator-role-namespaced
  namespace: default
rules:
- apiGroups:
  - trulia.com
  resources:
  - kopfpeerings
  verbs:
  - list
  - watch
  - patch
  - get
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - trulia.com
  resources:
  - vpce-operators
  - vpcendpoints
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - create
  - delete
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: vpce-operator-role-cluster
rules:
- apiGroups:
  - trulia.com
  resources:
  - clusterkopfpeerings
  verbs:
  - list
  - watch
  - patch
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - get
- apiGroups:
  - trulia.com
  resources:
  - vcpe-operators
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: vpce-operator-rolebinding-namespaced
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vpce-operator-role-namespaced
subjects:
- kind: ServiceAccount
  name: vpce-operator-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vpce-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vpce-operator-role-cluster
subjects:
- kind: ServiceAccount
  name: vpce-operator-account
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpce-operator
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: vpce-operator
  template:
    metadata:
      labels:
        application: vpce-operator
    spec:
      serviceAccountName: vpce-operator-account
      containers:
      - name: vpce-operator
        image: sepulworld/vpce-operator:0.0.1-30
      terminationGracePeriodSeconds: 3
```

Apply the same yaml to k8s 1.14.6 and get the error reported above

Are there any specific settings that work on 1.14.6 but changed to work with 1.15.4?

## Specifications

  - Platform:
  - Kubernetes version: *(use `kubectl version`)*
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
  - Python version: *(use `python --version`)*
```
python:3.7
```
  - Python packages installed: *(use `pip freeze --all`)*

```
aiohttp==3.6.2
aiojobs==0.2.2
astroid==2.3.1
async-timeout==3.0.1
attrs==19.2.0
autoflake==1.3.1
boto3==1.9.249
botocore==1.12.249
cachetools==3.1.1
certifi==2019.9.11
chardet==3.0.4
Click==7.0
docutils==0.15.2
entrypoints==0.3
flake8==3.7.8
google-auth==1.6.3
idna==2.8
iso8601==0.1.12
isort==4.3.21
jmespath==0.9.4
kopf==0.21
kubernetes==10.0.1
lazy-object-proxy==1.4.2
mccabe==0.6.1
multidict==4.5.2
oauthlib==3.1.0
pip==19.0.3
pyasn1==0.4.7
pyasn1-modules==0.2.7
pycodestyle==2.5.0
pyflakes==2.1.1
pykube-ng==19.10.0
pylint==2.4.2
pylint-common==0.2.5
pylint-plugin-utils==0.6
python-dateutil==2.8.0
PyYAML==5.1.2
requests==2.22.0
requests-oauthlib==1.2.0
rsa==4.0
s3transfer==0.2.1
setuptools==40.8.0
six==1.12.0
typed-ast==1.4.0
urllib3==1.25.6
websocket-client==0.56.0
wrapt==1.11.2
yarl==1.3.0
```

Any help appreciated! I have been struggling to figure out root cause of this issue.

**Comment by sepulworld** [comment]
I was able to apply the Yaml to Docker for Mac running k8s 1.14.3 and app started fine as well. Any good debugging tips for perhaps turning in audit logs? I'm presently not seeing any errors in the k8s api server logs.

**Comment by sepulworld** [comment]
I think I figured it out

Needed to change the watching rule to match the resource name properly... changed to:
```
  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [trulia.com]
    resources: [vpcendpoints]
    verbs: [list, watch, patch, get]
```
Works now. By the way, love the project. Much more enjoyable to use than kubebuilder!
