### ISSUE TITLE
error about 'pykube.KubeConfig' that doesn't exist o.O

### ISSUE THREAD

**Issue by Dmitry1987** [zalando-incubator/kopf#215]
kopf fails always on this line:

https://github.com/zalando-incubator/kopf/blob/e1c995720a7b4be584a948ca1513397f8a89fd5f/kopf/clients/auth.py#L11

when I follow the documentation tutorial (from here https://kopf.readthedocs.io/en/latest/walkthrough/starting/), and then add the EKS workaround (the `kopf.clients.auth.get_pykube_cfg = my_auth_cfg` thingy to override with my .kube/config content)  the run fails with:
```
kopf run main.py --verbose

Traceback (most recent call last):
  File "/usr/local/bin/kopf", line 7, in <module>
    from kopf.cli import main
  File "/usr/local/lib/python3.7/site-packages/kopf/__init__.py", line 9, in <module>
    from kopf import (
  File "/usr/local/lib/python3.7/site-packages/kopf/on.py", line 17, in <module>
    from kopf.reactor import handling
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 23, in <module>
    from kopf.clients import patching
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/patching.py", line 6, in <module>
    from kopf import config
  File "/usr/local/lib/python3.7/site-packages/kopf/config.py", line 6, in <module>
    from kopf.engines import logging as logging_engine
  File "/usr/local/lib/python3.7/site-packages/kopf/engines/logging.py", line 14, in <module>
    from kopf.engines import posting
  File "/usr/local/lib/python3.7/site-packages/kopf/engines/posting.py", line 23, in <module>
    from kopf.clients import events
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/events.py", line 9, in <module>
    from kopf.clients import auth
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/auth.py", line 11, in <module>
    _pykube_cfg: Optional[pykube.KubeConfig] = None
AttributeError: module 'pykube' has no attribute 'KubeConfig'
```

I made sure to check if I have the pykube-ng installed: 
```
pip3 install pykube-ng --upgrade
Requirement already up-to-date: pykube-ng in /usr/local/lib/python3.7/site-packages (19.10.0)
Requirement already satisfied, skipping upgrade: PyYAML in /usr/local/lib/python3.7/site-packages (from pykube-ng) (3.13)
Requirement already satisfied, skipping upgrade: requests>=2.12 in /usr/local/lib/python3.7/site-packages (from pykube-ng) (2.19.1)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.12->pykube-ng) (2.7)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests>=2.12->pykube-ng)(3.0.4)
Requirement already satisfied, skipping upgrade: urllib3<1.24,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests>=2.12->pykube-ng)(1.23)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.12->pykube-ng) (2018.8.13)
```

And that all dependencies are installed:
```
pip3 install kopf --upgrade

Requirement already up-to-date: kopf in /usr/local/lib/python3.7/site-packages (0.22)
Requirement already satisfied, skipping upgrade: click in /usr/local/lib/python3.7/site-packages (from kopf) (6.7)
Requirement already satisfied, skipping upgrade: iso8601 in /usr/local/lib/python3.7/site-packages (from kopf) (0.1.12)
Requirement already satisfied, skipping upgrade: aiojobs in /usr/local/lib/python3.7/site-packages (from kopf) (0.2.2)
Requirement already satisfied, skipping upgrade: pykube-ng>=0.27 in /usr/local/lib/python3.7/site-packages (from kopf) (19.10.0)
Requirement already satisfied, skipping upgrade: aiohttp>=2.3.0 in /usr/local/lib/python3.7/site-packages (from aiojobs->kopf) (3.6.2)
Requirement already satisfied, skipping upgrade: PyYAML in /usr/local/lib/python3.7/site-packages (from pykube-ng>=0.27->kopf) (3.13)
Requirement already satisfied, skipping upgrade: requests>=2.12 in /usr/local/lib/python3.7/site-packages (from pykube-ng>=0.27->kopf) (2.19.1)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.5 in /usr/local/lib/python3.7/site-packages (from aiohttp>=2.3.0->aiojobs->kopf) (4.5.2)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /usr/local/lib/python3.7/site-packages (from aiohttp>=2.3.0->aiojobs->kopf) (18.1.0)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/site-packages (from aiohttp>=2.3.0->aiojobs->kopf) (3.0.1)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/site-packages (from aiohttp>=2.3.0->aiojobs->kopf) (1.3.0)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in /usr/local/lib/python3.7/site-packages (from aiohttp>=2.3.0->aiojobs->kopf)(3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.12->pykube-ng>=0.27->kopf) (2.7)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.12->pykube-ng>=0.27->kopf) (2018.8.13)
Requirement already satisfied, skipping upgrade: urllib3<1.24,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests>=2.12->pykube-ng>=0.27->kopf) (1.23)
```

What am I doing wrong? Any ideas?

**Comment by nolar** [comment]
@Dmitry1987 It is hard to say without seeing the project. 

May it be so that the is an arbitrary `pykube.py` file/script in the root project folder or in the current directory?

Can you please execute this?

```
python -c 'import pykube; print(pykube.__file__); print(pykube.KubeConfig);'
````

Does this error happen without the function monkey-patching?

**Comment by Dmitry1987** [comment]
Weird, it says the same:
```
python3.7 -c 'import pykube; print(pykube.__file__); print(pykube.KubeConfig);'
None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'pykube' has no attribute 'KubeConfig'
```
No there's no pykube.py, but I installed first the old pykube, then deleted it when I found the pykube-ng, can you please share the pip freeze of a working configuration?  So I'll change my versions if they're not good.

Mine is `pykube-ng==19.10.0` and 
```
kopf==0.22
kubernetes==7.0.0
```

No it doesn't happen unless I try to monkey-patch the auth.  When I comment out the auth patch, and run in the cluster, it works fine. But I can't do local development of the operator that way.

**Comment by Dmitry1987** [comment]
For now I build a docker image, and apply it to the operator in K8s, that way working with it. It's okay no big deal, but could be useful to figure out the authorization from local machine.

**Comment by nolar** [comment]
@Dmitry1987 

I see `None` was printed. That was totally unexpected.

Nevertheless, this explanation with just-pykube installed would explain it. When two libraries provide the same packages/modules, this never ends well in Python. Most likely, those are the remains of the previous library overwritten by a new library. 

The easiest way is to just recreate the virtualenv from scratch, with only pykube-ng installed this time.

Or you can try to clean the virtualenv manually:

```
pip install pykube-ng
pip uninstall pykube-ng
pip install pykube
pip uninstall pykube
```

Now, install pykube-ng and try the same python call to check if it works.

If it does not, then go to `.../site-packages/` of your virtualenv, and find everything named after pykube (any of them), and delete it.

All in all, this seems like a pykube-ng's issue, not a Kopf's issue. `pykube.KubeConfig` is expected to be there.

**Comment by Dmitry1987** [comment]
Got it, I'll try a clean virtualenv, thanks!
