### ISSUE TITLE
ValueError: Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL

### ISSUE THREAD

**Issue by chungktran** [zalando-incubator/kopf#242]
## Expected Behavior
kopf to run normall

## Actual Behavior
kopf throws error `ValueError: Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL`.

Please note that this error occurs when using kopf with k3s. However, I don't think k3s is the problem here but rather that it's using username/password authentication instead token.

## Steps to Reproduce the Problem

  1. Run kopf with or without `--dev` flag

## Specifications

  - Platform: Linux
  - Kubernetes version: v1.16.0
  - Python version: 3.7.4
  - Python packages installed: *(use `pip freeze --all`)*

```
Package           Version
----------------- ---------
aiohttp           3.6.2
aiojobs           0.2.2
async-timeout     3.0.1
attrs             19.3.0
cachetools        3.1.1
certifi           2019.9.11
chardet           3.0.4
Click             7.0
google-auth       1.7.1
idna              2.8
iso8601           0.1.12
kopf              0.23rc4
kubernetes        10.0.1
multidict         4.5.2
oauthlib          3.1.0
pip               19.3.1
pyasn1            0.4.7
pyasn1-modules    0.2.7
pykube-ng         19.10.0
python-dateutil   2.8.1
PyYAML            5.1.2
requests          2.22.0
requests-oauthlib 1.3.0
rsa               4.0
setuptools        41.6.0
six               1.13.0
typing-extensions 3.7.4.1
urllib3           1.25.7
websocket-client  0.56.0
wheel             0.33.6
yarl              1.3.0
```

Stack Trace
```
$ kopf run release.py
[2019-11-18 11:35:20,726] kopf.reactor.activit [INFO    ] Initial authentication has been initiated.
[2019-11-18 11:35:20,779] kopf.activities.auth [INFO    ] Handler 'login_via_pykube' succeeded.
[2019-11-18 11:35:20,806] kopf.activities.auth [INFO    ] Handler 'login_via_client' succeeded.
[2019-11-18 11:35:20,807] kopf.reactor.activit [INFO    ] Initial authentication has finished.
Traceback (most recent call last):
  File "/home/ctran/.venv/release/bin/kopf", line 8, in <module>
    sys.exit(main())
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/cli.py", line 31, in wrapper
    return fn(*args, **kwargs)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/cli.py", line 78, in run
    vault=__controls.vault,
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py", line 113, in run
    vault=vault,
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py", line 153, in operator
    vault=vault,
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py", line 239, in spawn_tasks
    standalone=standalone, namespace=namespace, name=peering_name,
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/engines/peering.py", line 116, in detect
    if await Peer._is_peering_exist(name=PEERING_DEFAULT_NAME, namespace=namespace):
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/engines/peering.py", line 158, in _is_peering_exist
    obj = await fetching.read_obj(resource=resource, namespace=namespace, name=name, default=None)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/clients/auth.py", line 34, in wrapper
    return await fn(*args, **kwargs, session=session)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/clients/fetching.py", line 57, in read_obj
    url=resource.get_url(server=session.server, namespace=namespace, name=name),
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/aiohttp/client.py", line 442, in _request
    raise ValueError("Cannot combine AUTHORIZATION header "
ValueError: Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL
Task was destroyed but it is pending!
task: <Task pending coro=<_root_task_checker() running at /home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py:418> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f66186b3250>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<_startup_cleanup_activities() running at /home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py:496> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f661869c9d0>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<_stop_flag_checker() running at /home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py:447> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f661869c050>()]>>
```

kobeconfig
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: MASKED
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: MASKED
    username: admin
```

**Comment by nolar** [comment]
@chungktran Can you please try it with the new `master`, or [`kopf==0.23rc5`](https://github.com/zalando-incubator/kopf/releases/tag/0.23rc5)?

**Comment by chungktran** [comment]
@nolar Looks good. Error is gone. Thanks for fixing this.
