### ISSUE TITLE
Crash on startup when peering CRDs not present

### ISSUE THREAD

**Issue by jerith** [zalando-incubator/kopf#251]
## Expected Behavior

Prior to 0.23.1, running without `--standalone` and without the peering CRD(s) resulted in this warning being logged:
```
[2019-11-21 10:10:42,317] kopf.engines.peering [WARNING ] Default peering object not found, falling back to the standalone mode.
```
Thereafter, the operator continued to run in standalone mode.

## Actual Behavior

After updating to 0.23.1, running without `--standalone` and without the peering CRD(s) results in the following exception being logged:
```
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://10.107.133.10:6443/apis/zalando.org/v1')
```
Thereafter, kopf logs some `Task was destroyed but it is pending!` messages and exits.

## Steps to Reproduce the Problem

Here's a complete repro session (with some output elided for brevity). I've separated each command and its output into its own block for readability, but I ran them one after the other with nothing else in between.
```
[10:19|jerith@meklon] ~% mktmpenv
 ...
This is a temporary environment. It will be deleted when you run 'deactivate'.
```
```
(tmp-ef38f0b16d2676a) [10:19|jerith@meklon] ~/.virtualenvs/tmp-ef38f0b16d2676a% pip install kopf==0.23
 ...
Successfully installed PyYAML-5.1.2 aiohttp-3.6.2 aiojobs-0.2.2 async-timeout-3.0.1 attrs-19.3.0 certifi-2019.9.11 chardet-3.0.4 click-7.0 idna-2.8 iso8601-0.1.12 kopf-0.23 multidict-4.6.0 pykube-ng-19.10.0 requests-2.22.0 typing-extensions-3.7.4.1 urllib3-1.25.7 yarl-1.3.0
(tmp-ef38f0b16d2676a) [10:20|jerith@meklon] ~/.virtualenvs/tmp-ef38f0b16d2676a% echo '# This operator has no handlers.' > empty.py
```
```
(tmp-ef38f0b16d2676a) [10:20|jerith@meklon] ~/.virtualenvs/tmp-ef38f0b16d2676a% kopf run --verbose empty.py
[2019-11-21 10:20:39,828] kopf.reactor.activit [INFO    ] Initial authentication has been initiated.
[2019-11-21 10:20:39,829] kopf.activities.auth [DEBUG   ] Invoking handler 'login_via_pykube'.
[2019-11-21 10:20:39,840] kopf.activities.auth [DEBUG   ] Pykube is configured via kubeconfig file.
[2019-11-21 10:20:39,848] kopf.activities.auth [INFO    ] Handler 'login_via_pykube' succeeded.
[2019-11-21 10:20:39,848] kopf.reactor.activit [INFO    ] Initial authentication has finished.
[2019-11-21 10:20:40,081] kopf.engines.peering [WARNING ] Default peering object not found, falling back to the standalone mode.
^C[2019-11-21 10:20:43,315] kopf.reactor.running [INFO    ] Signal SIGINT is received. Operator is stopping.
[2019-11-21 10:20:43,315] kopf.reactor.running [DEBUG   ] Root task 'poster of events' is cancelled.
[2019-11-21 10:20:43,315] kopf.reactor.running [DEBUG   ] Root task 'credentials retriever' is cancelled.
[2019-11-21 10:20:43,316] kopf.reactor.running [DEBUG   ] Root tasks are stopped: finished normally; tasks left: set()
[2019-11-21 10:20:43,316] kopf.reactor.running [DEBUG   ] Hung tasks stopping is skipped: no tasks given.
```
```
(tmp-ef38f0b16d2676a) [10:20|jerith@meklon] ~/.virtualenvs/tmp-ef38f0b16d2676a% pip install kopf==0.23.1
 ...
Successfully installed kopf-0.23.1
```
```
(tmp-ef38f0b16d2676a) [10:20|jerith@meklon] ~/.virtualenvs/tmp-ef38f0b16d2676a% kopf run --verbose empty.py
[2019-11-21 10:20:56,587] kopf.reactor.activit [INFO    ] Initial authentication has been initiated.
[2019-11-21 10:20:56,588] kopf.activities.auth [DEBUG   ] Invoking handler 'login_via_pykube'.
[2019-11-21 10:20:56,597] kopf.activities.auth [DEBUG   ] Pykube is configured via kubeconfig file.
[2019-11-21 10:20:56,605] kopf.activities.auth [INFO    ] Handler 'login_via_pykube' succeeded.
[2019-11-21 10:20:56,605] kopf.reactor.activit [INFO    ] Initial authentication has finished.
Traceback (most recent call last):
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/bin/kopf", line 8, in <module>
    sys.exit(main())
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/cli.py", line 31, in wrapper
    return fn(*args, **kwargs)
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/cli.py", line 78, in run
    vault=__controls.vault,
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/reactor/running.py", line 113, in run
    vault=vault,
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/reactor/running.py", line 153, in operator
    vault=vault,
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/reactor/running.py", line 239, in spawn_tasks
    standalone=standalone, namespace=namespace, name=peering_name,
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/engines/peering.py", line 116, in detect
    if await Peer._is_peering_exist(name=PEERING_DEFAULT_NAME, namespace=namespace):
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/engines/peering.py", line 158, in _is_peering_exist
    obj = await fetching.read_obj(resource=resource, namespace=namespace, name=name, default=None)
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/clients/auth.py", line 39, in wrapper
    return await fn(*args, **kwargs, session=session)
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/clients/fetching.py", line 56, in read_obj
    is_namespaced = await discovery.is_namespaced(resource=resource, session=session)
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/clients/discovery.py", line 34, in is_namespaced
    info = await discover(resource=resource, session=session)
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/clients/discovery.py", line 19, in discover
    response.raise_for_status()
  File "/Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://10.107.133.10:6443/apis/zalando.org/v1')
Task was destroyed but it is pending!
task: <Task pending coro=<_root_task_checker() running at /Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/reactor/running.py:418> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1057fdd90>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<_startup_cleanup_activities() running at /Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/reactor/running.py:496> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1057f5610>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<_stop_flag_checker() running at /Users/jerith/.virtualenvs/tmp-ef38f0b16d2676a/lib/python3.7/site-packages/kopf/reactor/running.py:447> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1057f5410>()]>>
```
```
(tmp-ef38f0b16d2676a) [10:20|jerith@meklon] ~/.virtualenvs/tmp-ef38f0b16d2676a% kopf run --verbose --standalone empty.py
[2019-11-21 10:21:01,907] kopf.reactor.activit [INFO    ] Initial authentication has been initiated.
[2019-11-21 10:21:01,908] kopf.activities.auth [DEBUG   ] Invoking handler 'login_via_pykube'.
[2019-11-21 10:21:01,916] kopf.activities.auth [DEBUG   ] Pykube is configured via kubeconfig file.
[2019-11-21 10:21:01,924] kopf.activities.auth [INFO    ] Handler 'login_via_pykube' succeeded.
[2019-11-21 10:21:01,924] kopf.reactor.activit [INFO    ] Initial authentication has finished.
^C[2019-11-21 10:21:04,532] kopf.reactor.running [INFO    ] Signal SIGINT is received. Operator is stopping.
[2019-11-21 10:21:04,532] kopf.reactor.running [DEBUG   ] Root task 'poster of events' is cancelled.
[2019-11-21 10:21:04,532] kopf.reactor.running [DEBUG   ] Root task 'credentials retriever' is cancelled.
[2019-11-21 10:21:04,533] kopf.reactor.running [DEBUG   ] Root tasks are stopped: finished normally; tasks left: set()
[2019-11-21 10:21:04,533] kopf.reactor.running [DEBUG   ] Hung tasks stopping is skipped: no tasks given.
```

## Specifications

  - Platform:
  - Kubernetes version: client `v1.15.3`, server `v1.14.3`
  - Python version: `3.7.5`
  - Python packages installed: `kopf==0.23` or `kopf==0.23.1` and their deps in a fresh virtualenv

**Comment by nolar** [comment]
Thanks for reporting! It should be now hot-fixed in [0.23.2](https://github.com/zalando-incubator/kopf/releases/tag/0.23.2). Can you please test it?

I've created #253 to follow up with this unfortunate bugs more systematically.

**Comment by jerith** [comment]
Yup, that fixes it for us.

Thanks for the quick response, and thanks for a fantastic operator framework!

**Comment by nolar** [comment]
@jerith You are welcome!
