### ISSUE TITLE
Operator handler shows connection reset by peer.

### ISSUE THREAD

**Issue by rajivginotra** [zalando-incubator/kopf#263]
## Expected Behavior
The pod should respond immediately

## Actual Behavior
Connection reset by peer in middle of creating resources

## Steps to Reproduce the Problem
1. Create an operator pod and try to create resource but this leads to below traceback
  
## Specifications

  - Platform:Ubuntu 16.04
  - Kubernetes version: *(use `kubectl version`)* v1.15.1
  - Python version: *(use `python --version`)* 3.7.5
  - Python packages installed: *(use `pip freeze --all`)* 
aiohttp==3.5.4
aiojobs==0.2.2
async-timeout==3.0.1
attrs==19.1.0
cachetools==3.1.1
certifi==2019.6.16
chardet==3.0.4
Click==7.0
google-auth==1.6.3
idna==2.8
iso8601==0.1.12
kopf==0.20
kubernetes==10.0.0
multidict==4.5.2
oauthlib==3.0.2
pip==19.3.1
pyasn1==0.4.5
pyasn1-modules==0.2.5
pykube-ng==0.28
python-dateutil==2.8.0
PyYAML==5.1.1
requests==2.22.0
requests-oauthlib==1.2.0
rsa==4.0
setuptools==41.4.0
six==1.12.0
urllib3==1.25.3
websocket-client==0.56.0
wheel==0.33.6
yarl==1.3.0

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 368, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 368, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/queueing.py", line 148, in worker
    await handler(event=event)
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 131, in custom_object_handler
    await patching.patch_obj(resource=resource, patch=patch, body=body)
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/patching.py", line 31, in patch_obj
    cls = classes._make_cls(resource=resource)
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/classes.py", line 10, in _make_cls
    api_resources = api.resource_list(resource.api_version)['resources']
  File "/usr/local/lib/python3.7/site-packages/pykube/http.py", line 194, in resource_list
    r = self.get(version=api_version)
  File "/usr/local/lib/python3.7/site-packages/pykube/http.py", line 269, in get
    return self.session.get(*args, **self.get_kwargs(**kwargs))
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pykube/http.py", line 135, in send
    response = self._do_send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
```

**Comment by nolar** [comment]
@rajivginotra Can you please try the same with the most recent `kopf==0.23.2` (I see 0.20 in your list). There were quite a lot of changes, especially in [0.23](https://github.com/zalando-incubator/kopf/releases/tag/0.23), where the synchronous pykube/requests/urllib3 were removed from the internals, and asynchronous aiohttp is now used. This should have changed how the low-level TCP connections are performed.

Maybe related: #169 #204 (low-level connection issues during the API calls).

**Comment by rajivginotra** [comment]
> @rajivginotra Can you please try the same with the most recent `kopf==0.23.2` (I see 0.20 in your list). There were quite a lot of changes, especially in [0.23](https://github.com/zalando-incubator/kopf/releases/tag/0.23), where the synchronous pykube/requests/urllib3 were removed from the internals, and asynchronous aiohttp is now used. This should have changed how the low-level TCP connections are performed.
> 
> Maybe related: #169 #204 (low-level connection issues during the API calls).

Sure Nolar, the new kopf version looks stable now and we don't see the  above symptoms now. 
Thanks for your help
