### ISSUE TITLE
Upgrading from 0.21 to 0.24 raises ClientResponseError

### ISSUE THREAD

**Issue by smileisak** [zalando-incubator/kopf#292]
## Long story short

When upgrade kopf version from `0.21` to `0.24`the operator raises a `aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden'` Exception related to my CRD.

Everything worked fine until the version `0.23` and my account have a full access to the Kubernetes cluster.

## Description

<details><summary>The code snippet to reproduce the issue</summary>

```python
import kopf
```
</details>

<details><summary>The exact command to reproduce the issue</summary>

```bash
kopf run run.py --verbose
```
</details>

<details><summary>The full output of the command that failed</summary>

```
2020-01-15 16:43:50 Ismail kopf.reactor.running[76248] ERROR Root task 'watcher of applications.renault.org' is failed: ClientResponseError("403, message='Forbidden'")
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/__main__.py", line 9, in <module>
    cli.main()
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/cli.py", line 31, in wrapper
    return fn(*args, **kwargs)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/cli.py", line 78, in run
    vault=__controls.vault,
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/reactor/running.py", line 113, in run
    vault=vault,
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/reactor/running.py", line 155, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/reactor/running.py", line 341, in run_tasks
    await _reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/reactor/running.py", line 402, in _reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/reactor/running.py", line 418, in _root_task_checker
    await coro
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/reactor/queueing.py", line 101, in watcher
    async for event in watching.infinite_watch(resource=resource, namespace=namespace):
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/clients/watching.py", line 64, in infinite_watch
    async for event in streaming_watch(resource=resource, namespace=namespace):
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/clients/watching.py", line 80, in streaming_watch
    items, resource_version = await fetching.list_objs_rv(resource=resource, namespace=namespace)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/clients/auth.py", line 46, in wrapper
    return await fn(*args, **kwargs, session=session)
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/kopf/clients/fetching.py", line 101, in list_objs_rv
    response.raise_for_status()
  File "/Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 942, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden'
```
</details>

## Environment

* Kopf version: 

```
Name: kopf
Version: 0.23.2
Summary: Kubernetes Operator Pythonic Framework (Kopf)
Home-page: https://github.com/zalando-incubator/kopf
Author: Sergey Vasilyev
Author-email: sergey.vasilyev@zalando.de
License: MIT
Location: /Users/smile/Renault/gitlabee.dt.renault.com/cloud-migration/common/j2c-provision/env/lib/python3.7/site-packages
Requires: typing-extensions, iso8601, pykube-ng, aiojobs, click, aiohttp
```

* Kubernetes version: 

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Python version: `Python 3.7.4`
* OS/platform: `MacOS 1.15.1`

<details><summary>Python packages installed</summary>

```
adal==1.2.1
aiohttp==3.5.4
aiojobs==0.2.2
aioschedule==0.5.2
asn1crypto==0.24.0
aspy.yaml==1.3.0
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.1.0
cachetools==3.1.0
certifi==2018.11.29
cffi==1.12.2
cfgv==2.0.1
chardet==3.0.4
Click==7.0
coloredlogs==10.0
coverage==4.5.4
coverage-badge==1.0.1
cryptography==2.6.1
decorator==4.4.0
fut==0.4.2
google-api-python-client==1.7.8
google-auth==1.6.3
google-auth-httplib2==0.0.3
httplib2==0.12.1
humanfriendly==4.18
identify==1.4.8
idna==2.8
importlib-metadata==1.3.0
iso8601==0.1.12
jsonpath-ng==1.4.3
kopf==0.23.2
kubernetes==8.0.1
more-itertools==6.0.0
multidict==4.5.2
nodeenv==1.3.3
oauth2client==4.1.3
oauthlib==3.0.1
pep8==1.7.1
pip==19.2.3
pluggy==0.9.0
ply==3.11
pre-commit==1.20.0
protobuf==3.6.1
py==1.8.0
pyasn1==0.4.5
pyasn1-modules==0.2.4
pycodestyle==2.5.0
pycparser==2.19
PyJWT==1.7.1
pykube-ng==0.28
pyotp==2.2.7
pytest==4.3.0
pytest-cov==2.8.1
python-anticaptcha==0.3.1
python-dateutil==2.8.0
python-ldap==3.2.0
pytz==2019.1
PyYAML==3.13
requests==2.21.0
requests-oauthlib==1.2.0
rsa==4.0
setuptools==41.2.0
six==1.12.0
toml==0.10.0
typing-extensions==3.7.4.1
tzlocal==2.0.0
uritemplate==3.0.0
urllib3==1.24.1
urllib3-mock==0.3.3
virtualenv==16.7.9
websocket-client==0.55.0
wheel==0.33.6
yarl==1.3.0
zipp==0.6.0
```
</details>

**Comment by nolar** [comment]
Can you please also share the RBAC setup in relation to this CRD for the service account of this operator? (Specifically, I would like to see if the `list` verb is on the list next to the `watch` verb for that namespaces/cluster role.)

**Comment by smileisak** [comment]
@nolar the operator is running in my dev machine using my kubeconfig, i'm administrator of the kubernetes cluster.

Here is some additional details about who-can watch and list this crd.

```bash
$ kubectl who-can watch syncarcas
No subjects found with permissions to watch syncarcas assigned through RoleBindings

CLUSTERROLEBINDING                                    SUBJECT                             TYPE            SA-NAMESPACE
cluster-admin                                         system:masters                      Group
cluster-admin-binding                                 ismail.kaboubi-extern@renault.com   User
provisionner-j2c-operator                             provisionner-j2c-operator           ServiceAccount  j2c-operator
system:controller:clusterrole-aggregation-controller  clusterrole-aggregation-controller  ServiceAccount  kube-system
system:controller:generic-garbage-collector           generic-garbage-collector           ServiceAccount  kube-system
system:controller:resourcequota-controller            resourcequota-controller            ServiceAccount  kube-system
system:kube-controller-manager                        system:kube-controller-manager      User
tiller                                                tiller                              ServiceAccount  kube-system
```

```bash
$ kubectl who-can list syncarcas
No subjects found with permissions to list syncarcas assigned through RoleBindings

CLUSTERROLEBINDING                                    SUBJECT                             TYPE            SA-NAMESPACE
cluster-admin                                         system:masters                      Group
cluster-admin-binding                                 ismail.kaboubi-extern@renault.com   User
provisionner-j2c-operator                             provisionner-j2c-operator           ServiceAccount  j2c-operator
system:controller:clusterrole-aggregation-controller  clusterrole-aggregation-controller  ServiceAccount  kube-system
system:controller:generic-garbage-collector           generic-garbage-collector           ServiceAccount  kube-system
system:controller:namespace-controller                namespace-controller                ServiceAccount  kube-system
system:controller:resourcequota-controller            resourcequota-controller            ServiceAccount  kube-system
system:kube-controller-manager                        system:kube-controller-manager      User
tiller                                                tiller                              ServiceAccount  kube-system
```

**Comment by nolar** [comment]
@smileisak And all of these CLI commands work normally?

```
kubectl get -n default syncarcas
kubectl get -A syncarcas
kubectl get -A crds
```

I will try to reproduce it in GKE with v1.13.11-gke.14, but it looks strange: the only change after 0.23 that might be relevant is #250 (0.23->0.23.1). It works for us both in namespaced and cluster-scoped operators, but we use K8s 1.14+ and not in GKE. Maybe this issue is specific to the environment.

**Comment by nolar** [comment]
I tried in GKE with `1.13.11-gke.14` — works fine for me in a fresh new cluster, so I could not reproduce the issue to catch it.

Creating the Google Cloud credentials was a challenge though. I used this guide to create service accounts via Console, downloaded some secret JSON files, and used them as the `GOOGLE_APPLICATION_CREDENTIALS ` env var: https://cloud.google.com/docs/authentication/getting-started

And there, I tried both "Kubernetes Engine Admin" & "Kubernetes Engine Cluster Admin" roles (separately). Both do work.

But, while looking at this complicated system of permissions, I can assume that your credentials are configured somehow to not have these roles assigned. Unfortunately, I am not that much familiar with GCP authentication/authorisation systems to give any hints on how to set it up. 

But HTTP 403 errors suggests that it is indeed a configuration issue.

---

What caught my eye in your report is this:

```
kubernetes==8.0.1
pykube-ng==0.28
```

Installing these versions did not help me to reproduce the issue either. But previously, I had to install `pykube-ng[gcp]` extra to be able to connect at all.

**Side-note:** Kopf has removed both `kubernetes` & `pykube-ng` client libraries from its core since 0.23. However, when they are installed, it uses them to authenticate to a k8s cluster (see [Authentication/Piggybacking](https://kopf.readthedocs.io/en/latest/authentication/#piggybacking)) — this is especially important when using the sophisticated authentication mechanics like in GCP/GKE.

Can you make any of these two libraries work in the same environment? E.g. to get a list of your resources in a simple standalone few-lines script.

**Comment by smileisak** [comment]
@nolar sorry for the delay of my response, by adding the login handler everything worked fine.

```python
@kopf.on.login()
def login_fn(**kwargs):
    return kopf.login_via_client(**kwargs)
```
