### ISSUE TITLE
Embedded Example Not Working

### ISSUE THREAD

**Issue by cliffburdick** [zalando-incubator/kopf#357]
## Long story short

I'm trying to run the embedded example untouched, but getting exceptions thrown from urllib3. It is complaining about connection refused (I'm assuming to the k8s master).

## Description

I'm using the kubeconfig method as opposed to running in a pod, and get the output shown in the summary below.

kubectl works with kubeconfig:
```
root@d1ed5b91b225:/workspace/examples/12-embedded# kubectl get nodes
NAME                                 STATUS                        ROLES    AGE   VERSION
comp001    Ready                         master   83d   v1.14.7
comp002    Ready                         <none>   44d   v1.14.7
```

The output below shows it is configured with kubeconfig.

Output:
```
root@d1ed5b91b225:/workspace/examples/12-embedded# python example.py
Starting the main app.
Do the main app activity here. Step 1/3.
[2020-05-04 16:53:03,828] kopf.reactor.activit [INFO    ] Initial authentication has been initiated.
[2020-05-04 16:53:03,829] kopf.activities.auth [DEBUG   ] Activity 'login_via_pykube' is invoked.
[2020-05-04 16:53:03,850] kopf.activities.auth [DEBUG   ] Pykube is configured via kubeconfig file.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
[2020-05-04 16:53:03,854] kopf.activities.auth [INFO    ] Activity 'login_via_pykube' succeeded.
[2020-05-04 16:53:03,854] kopf.activities.auth [DEBUG   ] Activity 'login_via_client' is invoked.
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
[2020-05-04 16:53:03,871] kopf.activities.auth [DEBUG   ] Client is configured via kubeconfig file.
  File "/usr/local/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 944, in send
[2020-05-04 16:53:03,873] kopf.activities.auth [INFO    ] Activity 'login_via_client' succeeded.
[2020-05-04 16:53:03,874] kopf.reactor.activit [INFO    ] Initial authentication has finished.
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb195689940>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 103, in <module>
    main()
  File "example.py", line 52, in main
    _create_object(step)
  File "example.py", line 66, in _create_object
    api.create_namespaced_custom_object(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 183, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 275, in create_namespaced_custom_object_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 340, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 172, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 382, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 272, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 165, in request
    r = self.pool_manager.request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /apis/zalando.org/v1/namespaces/default/kopfexamples (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb195689940>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-05-04 16:53:03,905] kopf.engines.peering [WARNING ] Default peering object not found, falling back to the standalone mode.
[2020-05-04 16:53:03,906] kopf.reactor.running [WARNING ] OS signals are ignored: running not in the main thread.
^CException ignored in: <module 'threading' from '/usr/local/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt:
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/local/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):`
```

I can work around the problem by adding `config.load_kube_config()` and forcing it to load the config.

## Environment

* Kopf version: kopf, version 0.27rc5
* Kubernetes version: v1.14.7
* Python version: Python 3.8.2
* OS/platform: Ubuntu 18.04

<details><summary>Python packages installed</summary>

```
aiohttp==3.6.2
aiojobs==0.2.2
aresponses==2.0.0
async-timeout==3.0.1
asynctest==0.13.0
attrs==19.3.0
cachetools==4.1.0
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.2
codecov==2.0.22
coverage==4.5.4
coveralls==2.0.0
docopt==0.6.2
freezegun==0.3.15
google-auth==1.14.1
idna==2.9
iso8601==0.1.12
-e git+https://github.com/zalando-incubator/kopf.git@e81c10990fd4e32031edd7cea1f886ed5bb2e058#egg=kopf
kubernetes==11.0.0
more-itertools==8.2.0
multidict==4.7.5
mypy==0.770
mypy-extensions==0.4.3
oauthlib==3.1.0
packaging==20.3
pip==20.1
pluggy==0.13.1
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pykube-ng==20.4.1
pyparsing==2.4.7
pytest==5.3.5
pytest-aiohttp==0.3.0
pytest-asyncio==0.10.0
pytest-cov==2.8.1
pytest-mock==3.1.0
python-dateutil==2.8.1
PyYAML==5.3.1
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
setuptools==46.1.3
six==1.14.0
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.25.9
wcwidth==0.1.9
websocket-client==0.57.0
wheel==0.34.2
yarl==1.4.2
```
</details>

**Comment by eshepelyuk** [comment]
@cliffburdick it tries to reach k8s api at  localhost:80. I doubt your k8s api are exposed on this address.

**Comment by cliffburdick** [comment]
@eshepelyuk that definitely looked like a problem to me, but the output said it was using kubeconfig (which is not localhost). I figured since that's the case, it should know not to use it, right? There's nothing in the example pointing to localhost either.

**Comment by eshepelyuk** [comment]
@cliffburdick maybe you are using non standard auth ? Like oidc or smth ?
We use oidc - and there are issue i've opened about it.
Just trying to help to put your attention to this particular issue related to incorrect k8s api url.

**Comment by cliffburdick** [comment]
@eshepelyuk thanks. I'll try to see if I can find where that's coming from. We shouldn't be using any non-standard auth since it's a default kubeadm install without any kind of RBAC.

**Comment by eshepelyuk** [comment]
@cliffburdick you also may try minikube to check if the reason is realy about kubeadm

**Comment by cliffburdick** [comment]
Hi @eshepelyuk, I was able to "fix" it by adding a `config.load_kube_config()`. It's more of a workaround since the example seemed to say it was already using the kubeconfig.

**Comment by eshepelyuk** [comment]
@cliffburdick maybe config loading bug, but unfortunately i can't suggest anything useful anymore. Need to wait for maintainers.
