### ISSUE TITLE
Streaming request error caused operator crash

### ISSUE THREAD

**Issue by nolar** [zalando-incubator/kopf#369]
## Long story short

The operator failed at a streaming connection error.

## Description

```
[2020-05-25 10:44:44,924] kopf.reactor.running [ERROR ] Root task 'watcher of pods' is failed:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/kopf/reactor/running.py", line 453, in _root_task_checker
await coro
File "/usr/local/lib/python3.7/dist-packages/kopf/reactor/queueing.py", line 109, in watcher
async for raw_event in stream:
File "/usr/local/lib/python3.7/dist-packages/kopf/clients/watching.py", line 75, in infinite_watch
async for raw_event in stream:
File "/usr/local/lib/python3.7/dist-packages/kopf/clients/watching.py", line 112, in streaming_watch
async for raw_event in stream:
File "/usr/local/lib/python3.7/dist-packages/kopf/clients/watching.py", line 146, in continuous_watch
async for raw_input in stream:
File "/usr/local/lib/python3.7/dist-packages/kopf/clients/auth.py", line 78, in wrapper
async for item in fn(*args, **kwargs, context=context):
File "/usr/local/lib/python3.7/dist-packages/kopf/clients/watching.py", line 215, in watch_objs
sock_connect=settings.watching.connect_timeout,
File "/usr/local/lib/python3.7/dist-packages/aiohttp/client.py", line 504, in _request
await resp.start(conn)
File "/usr/local/lib/python3.7/dist-packages/aiohttp/client_reqrep.py", line 847, in start
message, payload = await self._protocol.read() # type: ignore # noqa
File "/usr/local/lib/python3.7/dist-packages/aiohttp/streams.py", line 591, in read
await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError
```

## Environment

* Kopf version: 0.26
* Kubernetes version: 1.17.4

**Comment by nolar** [comment]
Solved in https://github.com/nolar/kopf/pull/512, available since `kopf>=0.28rc2`
