### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loader'

### ISSUE THREAD

**Issue by chungktran** [zalando-incubator/kopf#393]
## Long story short

Getting `AttributeError: 'NoneType' object has no attribute 'loader'` error when running inside of k8s.

## Description

Kopf running fine when running outside of k8s. It does exactly what I wanted to do when running outside of the cluster, which is to delete pods that have an annotation sets to `"true"`. However, when built into a container and runs it in k8s the error below is thrown. 

```
Traceback (most recent call last):
  File "/usr/local/bin/kopf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 36, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 75, in run
    modules=modules,
  File "/usr/local/lib/python3.7/site-packages/kopf/utilities/loaders.py", line 36, in preload
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 580, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

<details><summary>The code snippet to reproduce the issue</summary>

```python
import kopf
import kubernetes

DEFAULT_ANNOTATION = 'kopf.example.com/restart'

@kopf.timer('example.com', 'v1', 'restarts', interval=10)
def restart(spec, status, logger, **kwargs):
    anno = spec.get('annotation', DEFAULT_ANNOTATION)
    coreV1 = kubernetes.client.CoreV1Api()
    pods = coreV1.list_pod_for_all_namespaces(watch=False)

    # Get pods that have opted-in annotation to be restart
    tbd_pods = [
        {
            'name': p.metadata.name,
            'namespace': p.metadata.namespace,
        }
        for p in pods.items
        if p.metadata.annotations and p.metadata.annotations.get(anno, '').lower() == 'true'
    ]
    
    for pod in pods:
        coreV1.delete_namespaced_pod(pod['name'], pod['namespace'])
```
</details>

<details><summary>The exact command to reproduce the issue</summary>

```bash
 kopf run --liveness http://:8080/healthz --verbose restarter.py
```
</details>

<details><summary>The full output of the command that failed</summary>

```
Traceback (most recent call last):
  File "/usr/local/bin/kopf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 36, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 75, in run
    modules=modules,
  File "/usr/local/lib/python3.7/site-packages/kopf/utilities/loaders.py", line 36, in preload
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 580, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```
</details>

## Environment

* Kopf version:  `kopf, version 0.27`
* Kubernetes version: `v1.17.5`
* Python version: `Python 3.8.5`
* OS/platform: `Linux x86_64 GNU/Linux`

<details><summary>Python packages installed</summary>

```
aiohttp==3.6.2
aiojobs==0.2.2
async-timeout==3.0.1
attrs==19.3.0
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
google-auth==1.20.1
idna==2.10
iso8601==0.1.12
kopf==0.27
kubernetes==11.0.0
logzero==1.5.0
multidict==4.7.6
oauthlib==3.1.0
pip==20.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pykube-ng==20.7.2
python-consul==1.1.0
python-dateutil==2.8.1
PyYAML==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
setuptools==49.2.0
six==1.15.0
typing-extensions==3.7.4.2
urllib3==1.25.10
websocket-client==0.57.0
wheel==0.34.2
yapf==0.30.0
yarl==1.5.1
```
</details>

**Comment by chungktran** [comment]
I figured out the issue.
