### ISSUE TITLE
issue running the first example

### ISSUE THREAD

**Issue by sebgoa** [zalando-incubator/kopf#76]
I tried the first example and got:

```
sebair: 01-minimal (master)$ kopf run example.py --verbose
[2019-05-27 09:05:16,862] kopf.config          [DEBUG   ] configured via kubeconfig file
[2019-05-27 09:05:18,429] kopf.reactor.peering [WARNING ] Default peering object not found, falling back to the standalone mode.
[2019-05-27 09:05:38,900] kopf.reactor.handlin [DEBUG   ] [default/kopf-example-1] First appearance: {'apiVersion': 'zalando.org/v1', 'kind': 'KopfExample', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"zalando.org/v1","kind":"KopfExample","metadata":{"annotations":{},"labels":{"somelabel":"somevalue"},"name":"kopf-example-1","namespace":"default"},"spec":{"duration":"1m","field":"value","items":["item1","item2"]}}\n'}, 'creationTimestamp': '2019-05-27T07:05:35Z', 'generation': 1, 'labels': {'somelabel': 'somevalue'}, 'name': 'kopf-example-1', 'namespace': 'default', 'resourceVersion': '235142214', 'selfLink': '/apis/zalando.org/v1/namespaces/default/kopfexamples/kopf-example-1', 'uid': 'd359fea7-804d-11e9-b655-42010a80024c'}, 'spec': {'duration': '1m', 'field': 'value', 'items': ['item1', 'item2']}}
[2019-05-27 09:05:38,900] kopf.reactor.handlin [DEBUG   ] [default/kopf-example-1] Adding the finalizer, thus preventing the actual deletion.
[2019-05-27 09:05:38,900] kopf.reactor.handlin [DEBUG   ] [default/kopf-example-1] Patching with: {'metadata': {'finalizers': ['KopfFinalizerMarker']}}
[2019-05-27 09:05:39,528] kopf.reactor.handlin [DEBUG   ] [default/kopf-example-1] Creation event: {'apiVersion': 'zalando.org/v1', 'kind': 'KopfExample', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"zalando.org/v1","kind":"KopfExample","metadata":{"annotations":{},"labels":{"somelabel":"somevalue"},"name":"kopf-example-1","namespace":"default"},"spec":{"duration":"1m","field":"value","items":["item1","item2"]}}\n'}, 'creationTimestamp': '2019-05-27T07:05:35Z', 'finalizers': ['KopfFinalizerMarker'], 'generation': 1, 'labels': {'somelabel': 'somevalue'}, 'name': 'kopf-example-1', 'namespace': 'default', 'resourceVersion': '235142219', 'selfLink': '/apis/zalando.org/v1/namespaces/default/kopfexamples/kopf-example-1', 'uid': 'd359fea7-804d-11e9-b655-42010a80024c'}, 'spec': {'duration': '1m', 'field': 'value', 'items': ['item1', 'item2']}}
[2019-05-27 09:05:39,530] kopf.reactor.handlin [DEBUG   ] [default/kopf-example-1] Invoking handler 'create_fn'.
And here we are! Creating: {'duration': '1m', 'field': 'value', 'items': ['item1', 'item2']}
[2019-05-27 09:05:39,532] kopf.reactor.handlin [INFO    ] [default/kopf-example-1] Handler 'create_fn' succeeded.
[2019-05-27 09:05:40,025] kopf.reactor.queuein [ERROR   ] functools.partial(<function custom_object_handler at 0x11012bf28>, lifecycle=<function asap at 0x1121862f0>, registry=<kopf.reactor.registry.GlobalRegistry object at 0x112110668>, resource=Resource(group='zalando.org', version='v1', plural='kopfexamples'), freeze=<asyncio.locks.Event object at 0x111c49550 [unset]>) failed with an exception. Ignoring the event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/queueing.py", line 126, in worker
    await handler(event=event)
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 195, in custom_object_handler
    await execute(lifecycle=lifecycle, registry=registry, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 321, in execute
    cause=cause,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 421, in _execute
    events.info(cause.body, reason='Success', message=f"Handler {handler.id!r} succeeded.")
  File "/usr/local/lib/python3.7/site-packages/kopf/events.py", line 70, in info
    return event(obj, reason=reason, message=message, type='Normal')
  File "/usr/local/lib/python3.7/site-packages/kopf/events.py", line 63, in event
    body=body,
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/events_v1beta1_api.py", line 60, in create_namespaced_event
    (data) = self.create_namespaced_event_with_http_info(namespace, body, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/events_v1beta1_api.py", line 151, in create_namespaced_event_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 364, in request
    body=body)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '867460c4-dad8-4005-a70c-49b05a682d8b', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 27 May 2019 07:05:37 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
```

**Comment by nolar** [comment]
@sebgoa  Thanks for reporting. Can you please tell which version of Kubernetes you have (output of `kubectl version`)? Do you have the k8s events somehow disabled?

**Comment by sebgoa** [comment]
It is on GKE: : v1.12.6-gke.11

python 3.7.2

I upgraded the kubernetes client to 9.0.0

**Comment by nolar** [comment]
@sebgoa Ok, thanks. 

Interesting. The 1.12 tests do run normally with Minikube ([link](https://travis-ci.org/zalando-incubator/kopf/jobs/537204454)).

I will try to figure out what is wrong. And will add a `--no-k8s-events` CLI option today, to disable this k8s-logging at all (it is an auxiliary feature, not mandatory).

**Comment by sebgoa** [comment]
thanks, I look forward to using kopf

**Comment by nolar** [comment]
Cause identified: GKE>=1.12 has `disable-legacy-endpoints=true` set by default, as per the official docs. As such, `v1beta1` API for events is disabled in GKE, only `v1` is available. Kopf used `v1beta1` API (for the reason of not paying attention to this topic).

Fixed in #81  — it switches to `v1`, and also disables `v1beta1` in our own minikube tests (just in case).

**Comment by nolar** [comment]
Released as `kopf==0.13`: https://github.com/zalando-incubator/kopf/releases/tag/0.13

@sebgoa Can you please upgrade (`pip install -U kopf`) and try again?

**Comment by nolar** [comment]
PS: I've tested this in my own GKE before and after the fix. Before, it was failing with the same error. After, it was working as expected.

**Comment by sebgoa** [comment]
Tested and it works as expected.

Thanks a bunch for the quick fix.
